services:
  postgres:
    image: 'postgres:18'
    environment:
      - 'POSTGRES_DB=roombook'
      - 'POSTGRES_USER=roombook'
      - 'POSTGRES_PASSWORD=roombook' # local development only
    ports:
      - '5432:5432'
